#' Run one decorator block
#'
#' @param api API object passed to the decorator implementation.
#' @param source Character vector of lines from the decorator line through the
#'   end of the chunk (typically includes `#*` comments and one top-level R
#'   expression).
#' @param file Source file path (for error messages).
#' @param line Line number of the decorator (for error messages).
#'
#' @return Value of evaluating the constructed decorator call (often `NULL`
#'   invisibly).
#'
#' @details
#' On parse failure, throws `stop()` with `basename(file)` and `line` in the
#' message.
#'
#' @keywords internal
run_decorator <- function(api, source, file, line) {
    decorator <- gsub("\\s+", " ", gsub("^[^@]+@", "", source[[1]]))
    decorator <- as.list(strsplit(decorator, " ")[[1]])
    expr <- tryCatch(
        {
            parse(text = source)[[1]]
        },
        error = function(e) {
            stop("Cannot parse code at ", basename(file), "@", line)
        }
    )
    args <- c(
        list(decorator[[1]], api, list(expr)), decorator[-1],
        list(file = file)
    )
    eval(do.call(call, args = args))
}

#' Scan a file for a given `#* @decorator` tag and evaluate each chunk
#'
#' @param api API object.
#' @param file Path to an R source file.
#' @param decorator Decorator name without `@` (e.g. `"openeo-process"`).
#'
#' @return `NULL`, invisibly.
#'
#' @keywords internal
process_decorators <- function(api, file, decorator) {
    source <- readLines(file)
    pattern <- paste0("^\\s*#\\*\\s+@", decorator, "\\s?")
    lines <- c(which(grepl(pattern, source)), length(source))
    for (i in seq_len(length(lines) - 1)) {
        run_decorator(
            api = api,
            source = source[seq(lines[[i]], lines[[i + 1]])],
            file = file,
            line = lines[[i]]
        )
    }
}

#' Sentinel formal used to distinguish missing arguments from defaults
#'
#' @return The name object taken from a dummy function's formal `x`.
#'
#' @keywords internal
empty_name <- function() {
    formals(function(x) {})[["x"]]
}

# decorators
# <decorator-function> :=
#    function(<api>, <expr>, [decorator-params...], <proc_file>)

#' Register an openEO process from `#* @openeo-process`
#'
#' @description
#' Reads or creates `processes/<process_id>.json` next to `file`, then registers
#' the process on `api` via `add_process()`.
#'
#' @param api API object.
#' @param expr Parsed expression; expected to be an assignment whose RHS is a
#'   `function(...) { ... }`.
#' @param ... Reserved for future decorator arguments.
#' @param file Path to the processes R file (used to resolve `processes/` dir).
#'
#' @return `NULL`, invisibly.
#'
#' @details
#' If the JSON file does not exist, builds a minimal openEO parameter list from
#' the function's formals. Throws from [stopifnot()] if directories or files are
#' missing after creation attempts.
#'
#' @keywords internal
`openeo-process` <- function(api, expr, ..., file) {
    # extract from list
    expr <- expr[[1]]
    fn_name <- as.character(expr[[2]])
    # check and create the directory
    dir <- file.path(dirname(path.expand(file)), "processes")
    if (!dir.exists(dir)) {
        dir.create(dir)
    }
    stopifnot(dir.exists(dir))
    # get the process json file
    process_file <- file.path(dir, paste0(fn_name, ".json"))
    # TODO: use some identification to detect if the file was generated by
    #  openeocraft or not.
    if (!file.exists(process_file)) {
        arg_names <- names(expr[[3]][[2]])
        arg_defaults <- unname(expr[[3]][[2]])
        process <- list(
            id = fn_name,
            parameters = lapply(seq_along(arg_names), function(i) {
                if (is.null(arg_defaults[[i]]) ||
                    (arg_defaults[[i]] != empty_name())) {
                    return(list(
                        name = arg_names[[i]],
                        default = arg_defaults[[i]],
                        optional = TRUE
                    ))
                }
                list(
                    name = arg_names[[i]],
                    optional = FALSE
                )
            })
        )
        jsonlite::write_json(
            x = process,
            path = process_file,
            pretty = TRUE,
            auto_unbox = TRUE,
            null = "null"
        )
    }
    stopifnot(file.exists(process_file))
    process <- jsonlite::read_json(process_file)
    add_process(api, process)
    invisible(NULL)
}
