name: openeocraft Unit Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Run R Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        run: |
          install.packages('devtools')
          install.packages('testthat')
          devtools::install_deps(dependencies = TRUE)
          devtools::install_local()
        shell: Rscript {0}

      - name: Run tests
        run: |
          library(testthat)
          test_dir("tests")
        shell: Rscript {0}
